[translator]
useInstructions = false
toChat = "simple"
roundTripSelect = false
roundTrip = false

[translator.server.openAI]
model = "gpt-5"

  [translator.relDefs]
  seq = [ ]

[translator.reasoningServer.openAI]
model = "o3-mini"

[[translator.pb.blend]]
[translator.pb.blend.similarSearch]
n = 8
descField = "docString"

[[translator.pb.blend]]
[translator.pb.blend.similarSearch]
n = 4
descField = "concise-description"

[[translator.pb.blend]]
[translator.pb.blend.similarSearch]
n = 4
descField = "description"

  [translator.params]
  temp = 1
  stopTokens = [ ]
  n = 8
  maxTokens = 1_600

[translator.messageBuilder.directBuilder]
userHead = "user"
headMessage = "You are a coding assistant who translates from natural language to Lean Theorem Prover code following examples. The translated code is preceded by `import Mathlib._`, so do not include import statements. Suppress proofs for brevity. Follow EXACTLY the examples given."
egsHead = "The following are some examples of statements and their translations (proofs are suppressed for brevity):"
egResponseHead = """
## Lean Code

"""
egQueryHead = """
## Natural language statement

"""


[logging]

[logging.translators]
[logging.translators.info]
io = true
file= false

[logging.translators.debug]
io = false
file = false